### ISSUE TITLE
CSV output code :)

### ISSUE THREAD

**Issue by ferazambuja** [alexh-name/bsec_bme680_linux#6]
Would you mind sharing your code that outputs the csv for the unicornhat hd? 
https://github.com/alexh-name/bme680_outputs

**Comment by ferazambuja** [comment]
Wrong place

**Comment by alexh-name** [comment]
I included a sample of what I use in the comment on the top of prettyBSEC.sh: https://github.com/alexh-name/bme680_outputs/blob/master/prettyBSEC.sh#L14-L21

You can simply replace all the `printf`s in bsec_bme680.c (https://github.com/alexh-name/bsec_bme680_linux/blob/master/bsec_bme680.c#L194-L203), recompile with `sh make.sh` and you should get an output like expected by prettyBSEC.sh.

I'm thinking of introducing command line switches to bsec_bme680, so that you could just toggle the kind of output.
